### ISSUE TITLE
Home page map view

### ISSUE THREAD

**Issue by Karyum** [WebAhead/wajjbat-frontend#4]
Implement a map using google maps on the homepage to show:
- [x] all the business on the map
- [x] show user location on the map
- [x] be able to click on the business marker and be presented with a popup 
  - [link for a guide with popups and markers](https://tomchentw.github.io/react-google-maps/#infobox)

### Stretch goal
- [x] Filter by distance, show businesses that are close to the user by `x` meters/kilometers radius
> So imagine using the 2km filter and then the map would zoom in/out to fit 2 kilometers radius in the screen
